/* Generated by MyraPad at 9/11/2026 1:30:38 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace Myra.Samples
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_panelContainer = new ScrollViewer();
			_panelContainer.Id = "_panelContainer";
			StackPanel.SetProportionType(_panelContainer, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalSeparator1 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "Scale";
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			_sliderScale = new HorizontalSlider();
			_sliderScale.Minimum = 0.2f;
			_sliderScale.Maximum = 4;
			_sliderScale.Value = 1;
			_sliderScale.Width = 500;
			_sliderScale.Id = "_sliderScale";

			_labelScale = new Label();
			_labelScale.Text = "3";
			_labelScale.Id = "_labelScale";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel1, 1);
			horizontalStackPanel1.Widgets.Add(_sliderScale);
			horizontalStackPanel1.Widgets.Add(_labelScale);

			var label2 = new Label();
			label2.Text = "Text Scaling";
			Grid.SetRow(label2, 1);

			var label3 = new Label();
			label3.Text = "None";

			var label4 = new Label();
			label4.Text = "Supersampling";

			var label5 = new Label();
			label5.Text = "SDF";

			_comboTextScaling = new ComboView();
			_comboTextScaling.Id = "_comboTextScaling";
			Grid.SetColumn(_comboTextScaling, 1);
			Grid.SetRow(_comboTextScaling, 1);
			_comboTextScaling.Widgets.Add(label3);
			_comboTextScaling.Widgets.Add(label4);
			_comboTextScaling.Widgets.Add(label5);

			var label6 = new Label();
			label6.Text = "Text Texture Filtering";
			Grid.SetRow(label6, 2);

			var label7 = new Label();
			label7.Text = "Nearest";

			var label8 = new Label();
			label8.Text = "Linear";

			var label9 = new Label();
			label9.Text = "Anisotropic";

			_comboTextTextureFiltering = new ComboView();
			_comboTextTextureFiltering.Id = "_comboTextTextureFiltering";
			Grid.SetColumn(_comboTextTextureFiltering, 1);
			Grid.SetRow(_comboTextTextureFiltering, 2);
			_comboTextTextureFiltering.Widgets.Add(label7);
			_comboTextTextureFiltering.Widgets.Add(label8);
			_comboTextTextureFiltering.Widgets.Add(label9);

			var label10 = new Label();
			label10.Text = "Image Texture Filtering";
			Grid.SetRow(label10, 3);

			var label11 = new Label();
			label11.Text = "Nearest";

			var label12 = new Label();
			label12.Text = "Linear";

			var label13 = new Label();
			label13.Text = "Anisotropic";

			_comboImageTextureFiltering = new ComboView();
			_comboImageTextureFiltering.Id = "_comboImageTextureFiltering";
			Grid.SetColumn(_comboImageTextureFiltering, 1);
			Grid.SetRow(_comboImageTextureFiltering, 3);
			_comboImageTextureFiltering.Widgets.Add(label11);
			_comboImageTextureFiltering.Widgets.Add(label12);
			_comboImageTextureFiltering.Widgets.Add(label13);

			var label14 = new Label();
			label14.Text = "Stylesheet";
			Grid.SetRow(label14, 4);

			var label15 = new Label();
			label15.Text = "Default";

			var label16 = new Label();
			label16.Text = "Default2X";

			_comboStylesheet = new ComboView();
			_comboStylesheet.Id = "_comboStylesheet";
			Grid.SetColumn(_comboStylesheet, 1);
			Grid.SetRow(_comboStylesheet, 4);
			_comboStylesheet.Widgets.Add(label15);
			_comboStylesheet.Widgets.Add(label16);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(horizontalStackPanel1);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_comboTextScaling);
			grid1.Widgets.Add(label6);
			grid1.Widgets.Add(_comboTextTextureFiltering);
			grid1.Widgets.Add(label10);
			grid1.Widgets.Add(_comboImageTextureFiltering);
			grid1.Widgets.Add(label14);
			grid1.Widgets.Add(_comboStylesheet);

			_propertyGridParameters = new PropertyGrid();
			_propertyGridParameters.Id = "_propertyGridParameters";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(grid1);
			horizontalStackPanel2.Widgets.Add(_propertyGridParameters);

			
			Widgets.Add(_panelContainer);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(horizontalStackPanel2);
		}

		
		private ScrollViewer _panelContainer;
		private HorizontalSlider _sliderScale;
		private Label _labelScale;
		private ComboView _comboTextScaling;
		private ComboView _comboTextTextureFiltering;
		private ComboView _comboImageTextureFiltering;
		private ComboView _comboStylesheet;
		private PropertyGrid _propertyGridParameters;
	}
}
