<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(AppTargetFramework)</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <RootNamespace>MyraExport</RootNamespace>
    <AssemblyName>myra-export</AssemblyName>
    <PackageId>myra-export</PackageId>
    <ToolCommandName>myra-export</ToolCommandName>
    <OutputPath>bin\MonoGame\$(Configuration)</OutputPath>
    <DefineConstants>$(DefineConstants);MONOGAME</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\MyraPad\Resources\*.cstemplate">
      <LogicalName>MyraPad.Resources.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\MyraPad\ExporterCS.cs" Link="ExporterCS.cs" />
    <Compile Include="..\MyraPad\Resources.cs" Link="Resources.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(AppMonoGameVersion)" />
    <PackageReference Include="System.CodeDom" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Myra\Myra.MonoGame.csproj" />
  </ItemGroup>
</Project>