/* Generated by MyraPad at 9/11/2026 10:19:46 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MyraPad.UI
{
	partial class FontEditorDialog: Dialog
	{
		private void BuildUI()
		{
			_textValue = new TextBox();
			_textValue.Readonly = true;
			_textValue.Width = 400;
			_textValue.Id = "_textValue";

			var label1 = new Label();
			label1.Text = "Size";
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			_spinSize = new SpinButton();
			_spinSize.Maximum = 100;
			_spinSize.Minimum = 4;
			_spinSize.Value = 32;
			_spinSize.Integer = true;
			_spinSize.Width = 50;
			_spinSize.Id = "_spinSize";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(_spinSize);

			var label2 = new Label();
			label2.Text = "Set Font From Stylesheet";

			_buttomSetFromStylesheet = new Button();
			_buttomSetFromStylesheet.Id = "_buttomSetFromStylesheet";
			_buttomSetFromStylesheet.Content = label2;

			var label3 = new Label();
			label3.Text = "Set Font From External File";

			_buttonSetFromFile = new Button();
			_buttonSetFromFile.Id = "_buttonSetFromFile";
			_buttonSetFromFile.Content = label3;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_textValue);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_buttomSetFromStylesheet);
			verticalStackPanel1.Widgets.Add(_buttonSetFromFile);

			
			Title = "Font Editor";
			Left = 552;
			Top = 312;
			Content = verticalStackPanel1;
		}

		
		private TextBox _textValue;
		private SpinButton _spinSize;
		private Button _buttomSetFromStylesheet;
		private Button _buttonSetFromFile;
	}
}
