using FontStashSharp;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Myra.Graphics2D;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using NvgSharp;
using Color = Microsoft.Xna.Framework.Color;

namespace Myra.Samples;

/// <summary>
/// Sample game demonstrating two different ways to implement rounded corners:
/// brushes generated by <see cref="BrushFactory"/> (nine-patch textures) and brushes drawn with
/// NvgSharp (vector rounded rectangles). Both solid and hollow (bordered) variants are shown.
/// A slider controls the zoom level so the difference between the approaches can be inspected up close.
/// </summary>
public class RoundedCornersGame : Game
{
	private const int CornerRadius = 16;
	private const int BorderWidth = 4;

	private readonly GraphicsDeviceManager _graphics;

	private Desktop _desktop;

	private NvgBrush _nvgSolidBrush;
	private NvgBrush _nvgHollowBrush;
	private HorizontalSlider _sliderScale;
	private Label _labelScale;
	private VerticalStackPanel _cards;

	private float _scale = 1f;

	private static readonly Color CardBackground = new Color(48, 120, 220);
	private static readonly Color CardFill = new Color(48, 120, 220, 120);

	public RoundedCornersGame()
	{
		_graphics = new GraphicsDeviceManager(this)
		{
			PreferredBackBufferWidth = 1200,
			PreferredBackBufferHeight = 800,
			// Depth24Stencil8 is required by NvgSharp for stencil-based stroke rendering
			PreferredDepthStencilFormat = DepthFormat.Depth24Stencil8
		};

		Window.AllowUserResizing = true;
		IsMouseVisible = true;
	}

	protected override void LoadContent()
	{
		base.LoadContent();

		FontSystemDefaults.FontRasterizationMode = FontRasterizationMode.SDF;
		MyraEnvironment.Game = this;

		_nvgSolidBrush = new NvgBrush();
		_nvgSolidBrush.PaintHandler = PaintNvgSolidBackground;

		_nvgHollowBrush = new NvgBrush();
		_nvgHollowBrush.PaintHandler = PaintNvgHollowBackground;

		_desktop = new Desktop
		{
			Background = new SolidBrush(new Color(22, 28, 42)),
			Root = BuildUi()
		};

#if MONOGAME && !ANDROID
		// Inform Myra that external text input is available
		// So it stops translating Keys to chars
		_desktop.HasExternalTextInput = true;

		// Provide that text input
		Window.TextInput += (s, a) =>
		{
			_desktop.OnChar(a.Character);
		};
#endif
	}

	protected override void Draw(GameTime gameTime)
	{
		base.Draw(gameTime);

		GraphicsDevice.Clear(Color.Black);
		_desktop.Render();
	}

	private Widget BuildUi()
	{
		var layout = new Panel
		{
			HorizontalAlignment = HorizontalAlignment.Stretch,
			VerticalAlignment = VerticalAlignment.Stretch,
			Padding = new Thickness(32)
		};

		var panel = new VerticalStackPanel();

		panel.Widgets.Add(new Label
		{
			Text = "Myra Rounded Corners",
			HorizontalAlignment = HorizontalAlignment.Center
		});

		panel.Widgets.Add(new HorizontalSeparator());

		_sliderScale = new HorizontalSlider
		{
			Minimum = 0.2f,
			Maximum = 4,
			Value = 1,
			Width = 400
		};
		_sliderScale.ValueChangedByUser += (s, a) => UpdateScale();

		_labelScale = new Label();

		panel.Widgets.Add(new HorizontalStackPanel
		{
			HorizontalAlignment = HorizontalAlignment.Center,
			Spacing = 8,
			Widgets =
			{
				{ new Label { Text = "Scale", VerticalAlignment = VerticalAlignment.Center } },
				_sliderScale,
				_labelScale
			}
		});

		panel.Widgets.Add(new HorizontalSeparator());

		// BrushFactory (nine-patch texture) brushes
		var solidFactoryCard = CreateCard("BrushFactory\nsolid rounded rect", BrushFactory.CreateSolidRoundedRect(color: CardBackground));
		var hollowFactoryCard = CreateCard("BrushFactory\nhollow rounded rect",
			BrushFactory.CreateHollowRoundedRect(borderWidth: BorderWidth, color: CardBackground, fillColor: CardFill));

		// NvgSharp (vector) brushes
		var solidNvgCard = CreateCard("NvgSharp\nsolid rounded rect", _nvgSolidBrush);
		var hollowNvgCard = CreateCard("NvgSharp\nhollow rounded rect", _nvgHollowBrush);

		_cards = new VerticalStackPanel
		{
			HorizontalAlignment = HorizontalAlignment.Center,
			VerticalAlignment = VerticalAlignment.Center,
			Spacing = 24
		};

		_cards.Widgets.Add(new HorizontalStackPanel
		{
			Spacing = 40,
			Widgets = { solidFactoryCard, hollowFactoryCard }
		});

		_cards.Widgets.Add(new HorizontalStackPanel
		{
			Spacing = 40,
			Widgets = { solidNvgCard, hollowNvgCard }
		});

		var cardsContainer = new Panel
		{
			ClipToBounds = true
		};
		StackPanel.SetProportionType(cardsContainer, ProportionType.Fill);
		cardsContainer.Widgets.Add(_cards);

		panel.Widgets.Add(cardsContainer);

		layout.Widgets.Add(panel);

		UpdateScale();

		return layout;
	}

	private void UpdateScale()
	{
		_scale = (float)_sliderScale.Value;
		_labelScale.Text = _scale.ToString("0.00");
		_cards.Scale = new Vector2(_scale);
	}

	/// <summary>
	/// Builds a demo card: a fixed-size <see cref="Panel"/> using the given brush as its
	/// background, with a caption label pinned to the bottom.
	/// </summary>
	private static Widget CreateCard(string caption, IBrush background)
	{
		var card = new Panel
		{
			Background = background,
			Width = 340,
			Height = 220,
			ClipToBounds = true
		};

		card.Widgets.Add(new Label
		{
			Text = caption,
			HorizontalAlignment = HorizontalAlignment.Center,
			VerticalAlignment = VerticalAlignment.Bottom,
			Margin = new Thickness(12),
			TextColor = new Color(255, 255, 255, 220)
		});

		return card;
	}

	/// <summary>
	/// Draws the NvgSharp solid background: a vector rounded rectangle filled with the card color.
	/// The radius is scaled along with the zoom level so it matches the nine-patch corners.
	/// </summary>
	private void PaintNvgSolidBackground(NvgContext vg, Point size)
	{
		var radius = CornerRadius * _scale;

		vg.SaveState();

		vg.BeginPath();
		vg.RoundedRect(0, 0, size.X, size.Y, radius);
		vg.FillColor(CardBackground);
		vg.Fill();

		vg.RestoreState();
	}

	/// <summary>
	/// Draws the NvgSharp hollow background: a vector rounded rectangle filled with the fill color
	/// and stroked with the card color. The radius and border width are scaled along with the zoom
	/// level so they match the nine-patch corners.
	/// </summary>
	private void PaintNvgHollowBackground(NvgContext vg, Point size)
	{
		var radius = CornerRadius * _scale;
		var borderWidth = BorderWidth * _scale;

		vg.SaveState();

		vg.BeginPath();
		vg.RoundedRect(0, 0, size.X, size.Y, radius);
		vg.FillColor(CardFill);
		vg.Fill();

		vg.BeginPath();
		vg.RoundedRect(0, 0, size.X, size.Y, radius);
		vg.StrokeColor(CardBackground);
		vg.StrokeWidth(borderWidth);
		vg.Stroke();

		vg.RestoreState();
	}
}